name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
jobs:

  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.function1 }}
      output2: ${{ steps.filter.outputs.function2 }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          function1:
            - 'function1/**'
          function2:
            - 'function2/**'

  deploy_source1:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.output1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: function1 
          source: ./function1/*

  deploy_source2:
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.output2 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: function2 
          source: ./function2/*
