name: deploy to lambda
on:
  push:
    branches:
      - master
jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      function1: ${{ steps.filter.outputs.function1 }}
      function2: ${{ steps.filter.outputs.function2 }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            function1:
              - 'function1/**'
            function2:
              - 'function2/**'

  function1:
    needs: changes
    if: ${{ needs.changes.outputs.function1 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: function1 
          source: ./function1/*


  function2:
    needs: changes
    if: ${{ needs.changes.outputs.function2 == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: function2 
          source: ./function2/*
